services:
    default.subscriber:
        class: Vidal\MainBundle\Service\DoctrineEventSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    vidal.digest_logger:
        class: Vidal\MainBundle\Service\DigestLogger
        arguments: [@service_container]

    drug.subscriber:
        class: Vidal\DrugBundle\Service\DoctrineEventSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connection: drug }

    drug.tag_total:
         class: Vidal\DrugBundle\Service\TagTotalService
         arguments: [@service_container]

    default.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: 'twig.extension' }

    vidal.twig_extension:
        class: Vidal\MainBundle\Service\TwigExtension
        tags:
            - { name: twig.extension }

    email.service:
          class: Vidal\MainBundle\Service\EmailService
          arguments: [@service_container, @templating]

    findDrug.service:
          class: Vidal\MainBundle\Service\FindDrugService
          arguments: [ @doctrine.orm.entity_manager ]

    lingua.service:
        class: Vidal\DrugBundle\Service\LinguaService

    elastica.service:
        class: Vidal\DrugBundle\Service\ElasticaService
        arguments: [@lingua.service]

    prevent:
        class: Vidal\MainBundle\Service\Prevent
        arguments: [@session]

    drug.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: drug }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]