services:
    lingua.service:
        class: Vidal\DrugBundle\Service\LinguaService

    elastica.service:
        class: Vidal\DrugBundle\Service\ElasticaService
        arguments: [@lingua.service]